#+TITLE: [Esami] Informatica @ DSS 2019/2020 - (E-N)

/Avvertenza! Tutte le informazioni  in questa pagina possono cambiare
per esigenze organizzative, e di sincronizzazione tra i tre canali./

* Modalità e date degli appelli 

#+begin_export html
<hr />
#+end_export

  *Modalità di esame telematiche*:  a causa dell'impossibilita di fare
  esami in sicurezza  negli edifici della sapienza,  gli esami saranno
  svolti sulla piattaforma [[https://exam.net][Exam.net]], con una simultanea teleconferenza
  su  Google  Meet per  la  verifica  dell'identità, dell'ambiente  di
  lavoro e per  comunicare col docente. Per la teleconferenza dovrete
  installare  e usare  Google  Meet su  *un  secondo dispositivo*,  ad
  esempio uno smartphone o un secondo computer. *NON VERRÀ USATO SEB*.

  [[https://www.uniroma1.it/it/documento/procedura-straordinaria-conseguente-allemergenza-sanitaria-covid-19-lo-svolgimento-degli][Guida per gli studenti alla piattaforma Exam.net]]

  [[file:docs/examnet-istruzioni-appello3.pdf][Istruzioni per la prova di programmazione]]

  1. Installare Google Meet sul secondi dispositivo.
  2. Poco  prima dell'esame verranno inviati  sull'email istituzionale
     *dei soli prenotati all'appello* gli  inviti per la conferenza in
     Google Meet.
  3. Contestualmente  (sull'email  istituzionale)  verrà
   comunicata una  chiave di  accesso per  l'esame da  utilizzare su
   [[https://exam.net][Exam.net]], e l'invito alla teleconferenza Google Meet. 
  4. La piattaforma [[https://exam.net][Exam.net]] ci segnala  se se passate a qualche altra
     applicazione.
  5. L'esame sarà  più o  meno  come al  solito (vedi  sotto), ma  la
    consegna avverrà tramite la piattaforma.

  *Attenzione: prova tecnica di esame il 25 Maggio 2020 alle 15:00*

#+begin_export html
<hr />
#+end_export

  L'esame sarà costituito da due prove, 

  - prova di teoria 
  - prova di programmazione

  e per  completare l'esame  sarà necessario  ottenere in  entrambe un
  voto non  inferiore a 18. Il  voto finale dell'esame sarà  una media
  artimetica  del  voto  delle  due prove.  Non  ci  saranno  esoneri.
  La prova pratica di programmazione  Python verrà svolta al computer,
  secondo  modalità  molto  simili  a  quelle  utilizzate  durante  le
  esercitazioni di laboratorio. Si consiglia di esercitarsi alla prova
  con le stesse modalità  descritte nelle esercitazioni di Laboratorio
  6, 7, 8, 9 e seguenti, utilizzando i file di test.

  Un eventuale colloquio orale è a discrezione del docente.

  Esempio di prova di teoria: ([[file:docs/esempio_prova_teoria.pdf][scarica]])

  Esempio di prova di programmazione: ([[file:docs/esempio_prova_programmazione.zip][scarica]])

  #+BEGIN_CENTER
  |---------+-----------+---------------+------------+------------------------|
  | Appello | Data      | Aula          |     Orario | Risultati              |
  |---------+-----------+---------------+------------+------------------------|
  | I       | 17/1/2020 | Aula 15 RM025 | 9:00-14:00 | ([[file:docs/risultati-2020.01.17.pdf][vedi qui]])             |
  | II      | 10/2/2020 | Aula 15 RM025 | 9:00-14:00 | ([[file:docs/risultati-2020.02.10.pdf][vedi qui]])             |
  | III     | 3/6/2020  | Exam.net      | 9:00-14:00 | ([[file:docs/risultati-2020.06.03.pdf][vedi qui]])             |
  | IV      | 6/7/2020  | Aula 15 RM025 | 9:00-14:00 | non ancora disponibili |
  | V       | 18/9/2020 | Aula 15 RM025 | 9:00-14:00 | non ancora disponibili |
  |---------+-----------+---------------+------------+------------------------|
  #+END_CENTER
  
  In ogni  data verranno svolte  entrambe le prove, secondo  un orario
  che va ancora  finalizzato, a seconda del numero di  studenti che si
  presenteranno. Ad esempio:

  - prova di teoria: dalle ore 9.00 alle 11.00
  - prova di programmazione: dalle ore 11.30 alle ore 13.30

  È  anche  possibile  svolgere  le   due  prove  in  appelli  diversi
  presentandosi, in un dato appello, per una sola di esse.

** Note  ulteriori

   Non è necessario  fare la prova scritta nello  stesso appello della
   prova di  programmazione. Ognuna  delle due prove  viene conservata
   *fino  all'appello  di  Settembre,   incluso*.  Quindi  ad  esempio
   è  possibile consegnare  lo scritto  nell'appello di  Gennaio e  la
   prova di programmazione in quello  di Luglio, e quindi verbalizzare
   il voto a Luglio.

   Se  si  consegna più  di  una  volta  una  delle due  prove,  viene
   mantenuto solo  il voto  più recente,  anche se  è più  basso delle
   prove precedenti.

* Appelli straordinari

  A Marzo e  a Ottobre si svolgeranno gli  appelli straordinari aperte
  solo a specifiche categorie di studenti, ovvero

  - studenti part-time,
  - studenti con disabilità e con D.S.A.,
  - studenti fuori corso, 
  - (*solo per l'appello di ottobre*) iscritti per l'A.A. 2019-2020 al
    terzo anno della laurea o al secondo anno della laurea magistrale.

  L'organizzazione di questi  appelli verrà decisa di  volta in volta,
  a  seconda del  numero  di iscritti.  Ad esempio  se  ci sono  pochi
  iscritti è possibile  che l'esame sia una prova orale  svolta in una
  giornata decisa collegialmente insieme agli studenti stessi.

