#+TITLE: [Esami] Informatica @ DSS 2019/2020 - (E-N)

/Avvertenza! Tutte le informazioni  in questa pagina possono cambiare
per esigenze organizzative, e di sincronizzazione tra i tre canali./

* Modalità e date degli appelli 

  L'esame sarà costituito da due prove, 

  - prova scritta 
  - prova pratica di programmazione

  e per  completare l'esame  sarà necessario  ottenere in  entrambe un
  voto non  inferiore a 18. Il  voto finale dell'esame sarà  una media
  artimetica  del  voto  delle  due prove.  Non  ci  saranno  esoneri.
  La prova pratica di programmazione  Python verrà svolta al computer,
  secondo  modalità  molto  simili  a  quelle  utilizzate  durante  le
  esercitazioni di laboratorio. Si consiglia di esercitarsi alla prova
  con le stesse modalità  descritte nelle esercitazioni di Laboratorio
  6, 7, 8, 9 e seguenti, utilizzando i file di test.

  Un eventuale colloquio orale è a discrezione del docente.


  #+BEGIN_CENTER
  |---------+-----------+---------------+------------+------------------------|
  | Appello | Data      | Aula          |     Orario | Risultati              |
  |---------+-----------+---------------+------------+------------------------|
  | I       | 17/1/2020 | Aula 15 RM025 | 9:00-14:00 | non ancora disponibili |
  | II      | 10/2/2020 | Aula 15 RM025 | 9:00-14:00 | non ancora disponibili |
  | III     | 3/6/2020  | Aula 15 RM025 | 9:00-14:00 | non ancora disponibili |
  | IV      | 6/7/2020  | Aula 15 RM025 | 9:00-14:00 | non ancora disponibili |
  | V       | 18/9/2020 | Aula 15 RM025 | 9:00-14:00 | non ancora disponibili |
  |---------+-----------+---------------+------------+------------------------|
  #+END_CENTER
  
  In ogni  data verranno svolte  entrambe le prove, secondo  un orario
  che va ancora  finalizzato, a seconda del numero di  studenti che si
  presenteranno. Ad esempio:

  - prova scritta: dalle ore 9.00 alle 11.00
  - prova di programmazione: dalle ore 11.30 alle ore 13.30

  È  anche  possibile  svolgere  le   due  prove  in  appelli  diversi
  presentandosi, in un dato appello, per una sola di esse.

** Note  ulteriori

   Non è necessario  fare la prova scritta nello  stesso appello della
   prova di  programmazione. Ognuna  delle due prove  viene conservata
   *fino  all'appello  di  Settembre,   incluso*.  Quindi  ad  esempio
   è  possibile consegnare  lo scritto  nell'appello di  Gennaio e  la
   prova di programmazione in quello  di Luglio, e quindi verbalizzare
   il voto a Luglio.

   Se  si  consegna più  di  una  volta  una  delle due  prove,  viene
   mantenuto solo  il voto  più recente,  anche se  è più  basso delle
   prove precedenti.

* Appelli straordinari

  A Marzo e  a Ottobre si svolgeranno gli  appelli straordinari aperte
  solo a specifiche categorie di studenti, ovvero

  - studenti part-time,
  - studenti con disabilità e con D.S.A.,
  - studenti fuori corso, 
  - (*solo per l'appello di ottobre*) iscritti per l'A.A. 2019-2020 al
    terzo anno della laurea o al secondo anno della laurea magistrale.

  L'organizzazione di questi  appelli verrà decisa di  volta in volta,
  a  seconda del  numero  di iscritti.  Ad esempio  se  ci sono  pochi
  iscritti è possibile  che l'esame sia una prova orale  svolta in una
  giornata decisa collegialmente insieme agli studenti stessi.

