#+TITLE: [Diario delle lezioni] Informatica @ DSS 2019/2020 - (E-N)

Qui potete trovare  tutte le informazioni riguardo  il contenuto delle
lezioni,  ed il  relativo  materiale. Tenete  d'occhio questa  pagina.

* <2019-09-30 Mon> Laboratorio 1

  Esercitazione da fare in laboratorio: [[file:docs/lab01.pdf][scarica]].

  *Lavoro  assegnato:*  leggere dai paragrafi 5.1 a 5.8 

* <2019-09-26 gio> Lezione 3 - Scrivere programmi 

  Recuperiamo alcune cose  che non siamo riusciti a  fare alla lezione
  precedente  per problemi  logistici.  Vediamo  l'uso delle  funzioni
  =type=, =print= e degli operatori su stringhe.

  Vediamo come  si definisce e si  usa una variable, e  poi cominciamo
  a scrivere programmi minimali su file, per poi eseguirli. Vediamo la
  differenza nell'output tra sessione interattiva e programma eseguito
  da file.

  *Lavoro  assegnato:*  provare a  scrivere  ed  eseguire sequenze  di
  istruzioni  salvate  su  file.  O  con  =pythonanywhere.com=  oppure
  installando python sul vostro computer.

* <2019-09-25 mer> Lezione 2 - Cos'è la programmazione

  Discutiamo prevemente la struttura di  un calcolatore e alcune delle
  persone  coinvolte nel  suo sviluppo.  Spieghiamo la  differenza tra
  linguaggi naturali e artificiali, linguaggi di alto e basso livello,
  linguaggi compilati e interpretati.
   
  Nella  seconda  parte  della   lezione  cominciamo  a  vedere  delle
  operazioni interattive con python.  In questo contesto discutiamo il
  concetto  di  valore e  tipo  del  dato,  e vediamo  come  costruire
  espressioni utilizzando operazioni (aritmetiche e non) tra dati.
  
  Brevemente  vediamo una  carrellata di  possibilità per  lavorare in
  ambiente python. 

  *Materiale didattico*

  Cos'è la programmazione: ([[file:docs/introprogrammazione-slides.pdf][schermo]]|[[file:docs/introprogrammazione-print.pdf][stampa]])
  
  Ambienti di lavoro python: ([[file:docs/usarepython-slides.pdf][schermo]]|[[file:docs/usarepython-print.pdf][stampa]])

  *Lavoro assegnato:* leggere il capitolo 2 del libro di testo.

* <2019-09-23 Mon> Lezione 1 - Introduzione

  Abbiamo introdotto il corso,  fornendo le informazioni logistiche di
  base. Poi abbiamo visto come  effettuare i primi passi nell'ambiente
  linux  del  laboratorio: come  trovare  i  programmi necessari  allo
  svolgimento delle esercitazioni e come utilizzare il terminale.
   
  *Materiale didattico*

  Introduzione: ([[file:docs/opening-slides.pdf][schermo]]|[[file:docs/opening-print.pdf][stampa]])
  
  Tutorial al laboratorio: ([[file:docs/tutorial_lab-slides.pdf][schermo]]|[[file:docs/tutorial_lab-print.pdf][stampa]])

  *Lavoro assegnato:* leggere il capitolo 1 del libro di testo.

